--- 
user: deploy
group: app_cmdrkeene
cwd: /opt/apps/cmdrkeene/current
log_file: /opt/apps/cmdrkeene/shared/log/mongrel.log
port: "8000"
environment: production
address: 127.0.0.1
pid_file: /opt/apps/cmdrkeene/shared/pids/mongrel.pid
servers: 2